const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('fs'),path=require('path'),os=require('os');const {spawn}=require('child_process'),{once}=require('events');
const {chromium,request,expect}=require('playwright/test');const bcrypt=require('bcryptjs');const {randomUUID}=require('crypto');
test('F5.5: citas y cierre integrado de fase 5',{timeout:240000},async t=>{
 const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'inscolar-f55-'));const protectedFiles=['data/db.json','test_puppeteer.js'].map(f=>[f,fs.existsSync(path.join(root,f))?fs.readFileSync(path.join(root,f)):null]);
 for(const f of ['server.js','routes','lib','public'])fs.cpSync(path.join(root,f),path.join(dir,f),{recursive:true});fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'dir');fs.mkdirSync(path.join(dir,'data'));
 const dbp=path.join(dir,'data/db.json'),db=JSON.parse(fs.readFileSync(path.join(root,'data/db.json'))),password='F55Test#2026';for(const u of db.users)Object.assign(u,{passwordHash:bcrypt.hashSync(password,4),estado:'Activo',mustChangePassword:false,mfaEnabled:false});
 db.appointments=[];db.appointmentSlots=[];db.drafts=[];db.enrollments=[];db.documents=[];db.notifications=[];db.logs=[];db.enrollmentReservations=[];db.enrollmentCapacities=[{id:'ecf55',institucionId:'i001',cicloEscolar:'2026-2027',grado:'1ro de Primaria',limite:20}];
 const date=require('../lib/appointment-service').dateKey(new Date(Date.now()+7*86400000));const month=date.slice(0,7);
 db.periods=[{id:'f55period',institucionId:'i001',cicloEscolar:'2026-2027',inscripcion:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString()},documentos:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString()},citas:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString(),limiteCitas:50},documentosRequeridos:[{nombre:'Acta F55',niveles:['Primaria'],formatos:['PDF'],maxMb:1}]}];
 fs.writeFileSync(dbp,JSON.stringify(db));fs.writeFileSync(path.join(dir,'fail.cjs'),"const fs=require('fs'),path=require('path'),rename=fs.renameSync;fs.renameSync=(a,b)=>{if(fs.existsSync(path.join(__dirname,'FAIL_SAVE')))throw Error('fallo inyectado');return rename(a,b);};");
 const sock=require('net').createServer();sock.listen(0,'127.0.0.1');await once(sock,'listening');const port=sock.address().port;await new Promise(r=>sock.close(r));const base=`http://127.0.0.1:${port}`;
 const server=spawn(process.execPath,['--require',path.join(dir,'fail.cjs'),'server.js'],{cwd:dir,env:{...process.env,PORT:String(port),DB_PATH:dbp},stdio:['ignore','pipe','pipe']});const contexts=[];let browser;
 try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',x=>{if(String(x).includes('corriendo en'))resolve()});server.once('error',reject);server.stderr.on('data',x=>reject(Error(String(x))));});
  async function login(id){const c=await request.newContext({baseURL:base});contexts.push(c);assert.equal((await c.post('/api/auth/login',{data:{email:db.users.find(u=>u.id===id).email,password}})).status(),200);return c;}
  const tutor=await login('u002'),tutor2=await login('u008'),staff=await login('u003'),other=await login('u005'),admin=await login('u001'),support=await login('u004');
  const avail=async(c=tutor,extra='')=>(await(await c.get(`/api/appointments/availability?institucionId=i001&mes=${month}${extra}`)).json()).slots;
  const get=async(c,id)=>(await(await c.get('/api/appointments/'+id)).json()).appointment;
  const post=(c,slot,extra={})=>c.post('/api/appointments',{data:{institucionId:'i001',motivo:'Entrevista de admisión',slotId:slot.id,requestId:randomUUID(),...extra}});
  const act=async(c,a,action,extra={})=>c.post(`/api/appointments/${a.id}/${action}`,{data:{version:(await get(c,a.id)).version,...extra}});
  let slots,a;
  await t.test('horarios explícitos, permisos y periodo; no inventa horarios',async()=>{assert.deepEqual(await avail(),[]);const data={periodId:'f55period',fecha:date,desde:'09:00',hasta:'17:00',duracionMinutos:30,capacidad:1};assert.equal((await other.post('/api/institutions/i001/appointment-slots',{data})).status(),403);assert.equal((await tutor.post('/api/institutions/i001/appointment-slots',{data})).status(),403);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data:{...data,fecha:'2020-01-01'}})).status(),400);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data})).status(),200);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data})).status(),409);slots=await avail();assert.equal(slots.length,16);assert.ok(slots.every(s=>s.disponibles===1&&s.fecha===date&&s.inicio.endsWith('Z')));});
  await t.test('rechaza fechas arbitrarias, pasadas y estudiantes ajenos',async()=>{assert.equal((await post(tutor,{id:'arbitraria'},{fechaHoraSolicitada:'2090-01-01T12:00:00Z'})).status(),400);const alien=db.students.find(s=>s.tutorId!=='u002');assert.equal((await post(tutor,slots[0],{studentId:alien.id})).status(),403);assert.equal((await other.get(`/api/appointments/availability?institucionId=i001&mes=${month}`)).status(),403);});
  await t.test('crear Pendiente ocupa un lugar; reintento no duplica ni notifica dos veces',async()=>{const requestId=randomUUID();const r=await post(tutor,slots[0],{requestId});assert.equal(r.status(),200);a=(await r.json()).appointment;assert.equal(a.estado,'Pendiente');assert.ok(!(await avail()).some(s=>s.id===slots[0].id));const replay=await post(tutor,slots[0],{requestId});assert.equal(replay.status(),200);assert.equal((await replay.json()).appointment.id,a.id);assert.equal((await post(tutor,slots[1],{requestId})).status(),409);const data=JSON.parse(fs.readFileSync(dbp));assert.equal(data.appointments.length,1);assert.equal(data.notifications.filter(n=>n.entityId===a.id).length,1);assert.ok(data.notifications[0].url.includes('/citas/'));});
  await t.test('aceptar mantiene capacidad; versiones y roles bloquean decisiones obsoletas',async()=>{assert.equal((await act(tutor,a,'aceptar')).status(),403);assert.equal((await admin.get('/api/appointments')).status(),403);assert.equal((await support.get('/api/appointments')).status(),403);assert.equal((await other.post(`/api/appointments/${a.id}/aceptar`,{data:{version:0}})).status(),403);assert.equal((await act(staff,a,'aceptar')).status(),200);assert.equal((await get(tutor,a.id)).estado,'Aceptada');assert.ok(!(await avail()).some(s=>s.id===slots[0].id));assert.equal((await staff.post(`/api/appointments/${a.id}/rechazar`,{data:{version:0,motivo:'Decisión anterior'}})).status(),409);});
  await t.test('último lugar entre dos clientes y dobles clics no sobrevende',async()=>{const responses=await Promise.all([post(tutor,slots[1]),post(tutor2,slots[1])]);assert.deepEqual(responses.map(r=>r.status()).sort(),[200,409]);const key=randomUUID();const double=await Promise.all([post(tutor,slots[2],{requestId:key}),post(tutor,slots[2],{requestId:key})]);assert.deepEqual(double.map(r=>r.status()),[200,200]);assert.equal((await double[0].json()).appointment.id,(await double[1].json()).appointment.id);});
  await t.test('reprogramación fallida conserva estado y horario; éxito vuelve a Pendiente',async()=>{const before=await get(tutor,a.id);assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[1].id})).status(),409);assert.deepEqual(await get(tutor,a.id),before);fs.writeFileSync(path.join(dir,'FAIL_SAVE'),'1');try{assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[3].id})).status(),500);assert.deepEqual(await get(tutor,a.id),before);}finally{fs.unlinkSync(path.join(dir,'FAIL_SAVE'));}assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[3].id})).status(),200);const after=await get(tutor,a.id);assert.equal(after.estado,'Pendiente');assert.equal(after.fechaHoraSolicitada,slots[3].inicio);assert.ok((await avail()).some(s=>s.id===slots[0].id));assert.ok(!(await avail()).some(s=>s.id===slots[3].id));assert.equal(after.historial.filter(h=>h.accion==='Cita reprogramada').length,1);});
  await t.test('rechazar requiere motivo y libera una sola vez con aviso visible',async()=>{assert.equal((await act(staff,a,'rechazar',{motivo:' '})).status(),400);assert.equal((await act(staff,a,'rechazar',{motivo:'No podemos atender esa fecha'})).status(),200);assert.equal((await act(staff,a,'rechazar',{motivo:'Reintento'})).status(),409);assert.ok((await avail()).some(s=>s.id===slots[3].id&&s.disponibles===1));assert.equal((await get(tutor,a.id)).motivoRechazo,'No podemos atender esa fecha');});
  await t.test('cancelar Pendiente o Aceptada libera una vez y conserva expediente',async()=>{for(const accepted of [false,true]){const r=await post(tutor,slots[4]);const b=(await r.json()).appointment;if(accepted)assert.equal((await act(staff,b,'aceptar')).status(),200);assert.equal((await tutor2.post('/api/appointments/'+b.id+'/cancelar',{data:{version:0}})).status(),403);assert.equal((await act(staff,b,'cancelar',{motivo:''})).status(),400);assert.equal((await act(tutor,b,'cancelar',{motivo:'Elegí otra fecha'})).status(),200);assert.equal((await act(tutor,b,'cancelar')).status(),409);assert.ok((await avail()).some(s=>s.id===slots[4].id&&s.disponibles===1));assert.equal((await get(tutor,b.id)).motivoCancelacion,'Elegí otra fecha');}});
  await t.test('aislamiento en lista, detalle, calendario y disponibilidad; cupos de inscripción intactos',async()=>{assert.equal((await tutor2.get('/api/appointments/'+a.id)).status(),403);const list=(await(await tutor.get('/api/appointments')).json()).appointments;assert.ok(list.every(a=>a.tutorId==='u002'));assert.equal((await other.get(`/api/institutions/i001/calendar?mes=${month}`)).status(),403);const calendar=await(await tutor2.get(`/api/institutions/i001/calendar?mes=${month}`)).json();assert.ok(Object.values(calendar.dias).flat().every(a=>a.tutorId==='u008'));assert.equal((await tutor2.get(`/api/appointments/availability?institucionId=i001&mes=${month}&excludeId=${a.id}`)).status(),403);assert.deepEqual(JSON.parse(fs.readFileSync(dbp)).enrollmentCapacities,db.enrollmentCapacities);});
  await t.test('vínculo de solicitud valida tutor, estudiante e institución sin exigir aceptación inventada',async()=>{let state=JSON.parse(fs.readFileSync(dbp));state.enrollments.push({id:'f55linked',tutorId:'u002',studentId:db.students.find(s=>s.tutorId==='u002').id,institucionId:'i001',estado:'Enviada',version:0,cicloEscolar:'2026-2027',gradoSolicitado:'1ro de Primaria',createdAt:new Date().toISOString()});fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await post(tutor2,slots[5],{enrollmentId:'f55linked'})).status(),403);assert.equal((await post(staff,slots[5],{enrollmentId:'f55linked'})).status(),200);assert.equal((await post(staff,slots[6])).status(),400);});
  await t.test('paginación, fecha y próximas/anteriores filtran antes de contar',async()=>{const all=await(await tutor.get('/api/appointments')).json();const p1=await(await tutor.get('/api/appointments?page=1&limit=2')).json(),p2=await(await tutor.get('/api/appointments?page=2&limit=2')).json();assert.equal(p1.total,all.total);assert.ok(p1.appointments.every(a=>!p2.appointments.some(b=>a.id===b.id)));const next=await(await tutor.get('/api/appointments?grupo=proximas&fecha='+date)).json();assert.ok(next.appointments.every(a=>['Pendiente','Aceptada'].includes(a.estado)));const old=await(await tutor.get('/api/appointments?grupo=anteriores')).json();assert.ok(old.appointments.every(a=>['Rechazada','Cancelada'].includes(a.estado)));assert.equal((await tutor.get('/api/appointments?page=0')).status(),400);});
  await t.test('citas Aceptadas conservan relación de calificación y contadores anteriores',async()=>{
   const r=await post(tutor2,slots[13]);const a=(await r.json()).appointment;assert.equal((await act(staff,a,'aceptar')).status(),200);
   assert.equal((await tutor2.post('/api/institutions/i001/ratings',{data:{estrellas:4,comentario:'Relación por cita aceptada'}})).status(),200);
   const summary=await(await admin.get('/api/analytics/summary')).json();const state=JSON.parse(fs.readFileSync(dbp));assert.equal(summary.citas.confirmadas,state.appointments.filter(a=>['Confirmada','Aceptada'].includes(a.estado)).length);
  });
  await t.test('eliminar un periodo sin citas retira franjas huérfanas y permite configurar el intervalo',async()=>{
   const nextDate=require('../lib/appointment-service').dateKey(new Date(Date.now()+8*86400000));let r=await admin.post('/api/institutions/i001/periods',{data:{cicloEscolar:'2027-2028'}});assert.equal(r.status(),200);const period=(await r.json()).period;
   r=await admin.put('/api/institutions/i001/periods/'+period.id,{data:{citas:{desde:nextDate+'T00:00:00-04:00',hasta:nextDate+'T23:59:59-04:00',limiteCitas:2}}});assert.equal(r.status(),200);
   const data={periodId:period.id,fecha:nextDate,desde:'08:00',hasta:'09:00',duracionMinutos:30,capacidad:1};assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data})).status(),200);
   assert.equal((await admin.delete('/api/institutions/i001/periods/'+period.id)).status(),200);
   assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data:{...data,periodId:'f55period'}})).status(),200);
  });
  await t.test('límite del periodo se distingue de capacidad por franja; reprogramar excluye solo su reserva',async()=>{
   let state=JSON.parse(fs.readFileSync(dbp));const active=state.appointments.filter(a=>['Pendiente','Aceptada','Confirmada'].includes(a.estado));state.periods[0].citas.limiteCitas=active.length;fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await avail()).length,0);
   const old=active.find(a=>a.tutorId==='u008'&&a.slotId===slots[13].id);assert.ok(old);assert.equal((await act(tutor2,old,'reprogramar',{slotId:slots[14].id})).status(),200);assert.equal((await get(tutor2,old.id)).estado,'Pendiente');assert.equal((await avail()).length,0);
   state=JSON.parse(fs.readFileSync(dbp));state.periods[0].citas.limiteCitas=50;fs.writeFileSync(dbp,JSON.stringify(state));
  });
  await t.test('franjas pasadas no se ofrecen ni reservan; citas legacy conservan las acciones por estado',async()=>{
   const state=JSON.parse(fs.readFileSync(dbp));const past={id:'past-slot',institucionId:'i001',periodId:'f55period',inicio:'2020-01-01T12:00:00Z',fin:'2020-01-01T12:30:00Z',capacidad:1};state.appointmentSlots.push(past);state.appointments.push({id:'legacy-past',tutorId:'u002',institucionId:'i001',estado:'Confirmada',fechaHoraSolicitada:'2020-01-01T12:00:00Z',motivo:'Seguimiento académico'});fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await post(tutor,past)).status(),409);assert.ok(!(await avail()).some(s=>s.id==='past-slot'));const legacy=await get(tutor,'legacy-past');assert.equal(legacy.estado,'Aceptada');assert.equal(legacy.acciones.cancelar,true);assert.equal((await act(tutor,legacy,'cancelar')).status(),200);assert.equal((await act(tutor,legacy,'cancelar')).status(),409);
  });
  if(process.env.F55_API_ONLY)return;
  browser=await chromium.launch();
  async function pageFor(id,options={}){const c=await browser.newContext(options);contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(8000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const u=db.users.find(u=>u.id===id);await p.goto(base+'/#/login');await p.locator('[name=email]').fill(u.email);await p.locator('[name=password]').fill(password);await p.locator('#login-form button[type=submit]').click();await expect(p.locator('.main')).toContainText(u.email);return {page:p,context:c,errors};}
  const go=(p,hash)=>p.evaluate(hash=>location.hash=hash,hash);
  const newForm=async p=>{await go(p,`#/app/citas/nueva?inst=i001&mes=${month}&fecha=${date}`);await p.locator('[name=slotId]').first().waitFor();};
  let uiAppointment;
  await t.test('personal configura franjas por calendario; errores conservan valores y teclado móvil',async()=>{
   const {page,errors}=await pageFor('u003',{viewport:{width:375,height:812},colorScheme:'dark'});await go(page,`#/app/instituciones/i001/calendario?mes=${month}`);await expect(page.locator('.appointment-available-list').first()).toBeVisible();
   await page.getByText('Configurar franjas de atención',{exact:true}).click();await page.locator('[name=fecha]').fill(date);await page.locator('[name=desde]').fill('18:00');await page.locator('[name=hasta]').fill('19:00');await page.locator('[name=capacidad]').fill('2');
   await page.route('**/appointment-slots',r=>r.fulfill({status:500,contentType:'application/json',body:'{"error":"Fallo de configuración"}'}));await page.getByRole('button',{name:'Crear horarios'}).click();await expect(page.locator('#appointment-config-error')).toContainText('Fallo');await expect(page.locator('[name=desde]')).toHaveValue('18:00');await page.unroute('**/appointment-slots');await page.getByRole('button',{name:'Crear horarios'}).click();await expect(page.locator('#appointment-slot-form')).toHaveCount(1);
   await expect(async()=>assert.ok((await avail()).some(s=>s.inicio===`${date}T22:00:00.000Z`&&s.disponibles===2))).toPass();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);assert.deepEqual(errors,[]);
  });
  await t.test('consulta fallida y mes sin horarios conservan notas, ofrecen reintento y lista con teclado',async()=>{
   const {page,errors}=await pageFor('u002',{viewport:{width:375,height:812},colorScheme:'dark'});await page.route('**/api/appointments/availability?*',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"No se pudo consultar horarios"}'}));await go(page,`#/app/citas/nueva?inst=i001&mes=${month}`);await page.locator('#cita-notes').fill('Estas notas deben conservarse');await expect(page.locator('#cita-availability')).toContainText('No se pudo consultar');await page.unroute('**/api/appointments/availability?*');await page.locator('#cita-check').click();await page.locator('[name=slotId]').first().waitFor();await expect(page.locator('#cita-notes')).toHaveValue('Estas notas deben conservarse');await page.locator('[name=slotId]').first().focus();await page.keyboard.press('Space');await expect(page.locator('#cita-submit')).toBeEnabled();await page.locator('#cita-month').fill('2099-01');await expect(page.locator('#cita-availability')).toContainText('No hay horarios');await expect(page.locator('#cita-submit')).toBeDisabled();await expect(page.locator('#cita-notes')).toHaveValue('Estas notas deben conservarse');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);assert.deepEqual(errors,[]);
  });
  await t.test('solicitud con resumen, doble clic y recarga conserva cita Pendiente',async()=>{
   const {page,errors}=await pageFor('u002');await newForm(page);await page.locator(`[name=slotId][value="${slots[7].id}"]`).check();await page.locator('#cita-notes').fill('Nota de solicitud UI');await page.locator('#cita-submit').click();await expect(page.getByRole('dialog')).toContainText('America/Santo_Domingo');
   const response=page.waitForResponse(r=>r.url().endsWith('/api/appointments')&&r.request().method()==='POST');await page.locator('#mod-confirm').evaluate(b=>{b.click();b.click();});uiAppointment=(await(await response).json()).appointment;await expect(page.locator('.appointment-state')).toHaveText('◷ Pendiente');await page.reload();await expect(page.locator('.main')).toContainText('Nota de solicitud UI');assert.equal(JSON.parse(fs.readFileSync(dbp)).appointments.filter(a=>a.id===uiAppointment.id).length,1);assert.deepEqual(errors,[]);
  });
  await t.test('último lugar ocupado después del resumen conserva selecciones y ofrece alternativas',async()=>{
   const {page,errors}=await pageFor('u002');await newForm(page);await page.locator(`[name=slotId][value="${slots[6].id}"]`).check();await page.locator('#cita-notes').fill('Conservar tras conflicto');await page.locator('#cita-submit').click();assert.equal((await post(tutor2,slots[6])).status(),200);await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-modal-error')).toContainText('ya no está disponible');await expect(page.locator('#mod-confirm')).toBeDisabled();await page.locator('#appointment-alternatives').click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#cita-notes')).toHaveValue('Conservar tras conflicto');await expect(page.locator(`[name=slotId][value="${slots[6].id}"]`)).toHaveCount(0);assert.deepEqual(errors,[]);
  });
  await t.test('rechazo fallido conserva motivo; éxito lo muestra al tutor',async()=>{
   const {page,errors}=await pageFor('u003');await go(page,'#/app/citas/'+uiAppointment.id+'/detalle');await page.locator('[data-appointment-action=rechazar]').click();await page.locator('#appointment-motive').fill('La institución no puede atender ese día');await page.route('**/appointments/'+uiAppointment.id+'/rechazar',r=>r.fulfill({status:500,contentType:'application/json',body:'{"error":"Fallo al rechazar"}'}));await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-modal-error')).toContainText('Fallo');await expect(page.locator('#appointment-motive')).toHaveValue('La institución no puede atender ese día');await page.unroute('**/appointments/'+uiAppointment.id+'/rechazar');await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-state')).toContainText('Rechazada');const owner=await pageFor('u002');await go(owner.page,'#/app/citas/'+uiAppointment.id+'/detalle');await expect(owner.page.locator('.main')).toContainText('La institución no puede atender ese día');await expect(owner.page.getByRole('button',{name:'Buscar otro horario'})).toBeVisible();assert.deepEqual(errors,[]);assert.deepEqual(owner.errors,[]);
  });
  await t.test('reprogramación UI conserva horario al fallar, luego vuelve a Pendiente y puede cancelar',async()=>{
   const created=(await(await post(tutor,slots[8])).json()).appointment;await act(staff,created,'aceptar');const {page,errors}=await pageFor('u002',{viewport:{width:375,height:812},colorScheme:'dark'});await go(page,'#/app/citas/'+created.id+'/detalle');await page.locator('[data-appointment-action=reprogramar]').click();await page.locator(`[name=slotId][value="${slots[9].id}"]`).check();await page.locator('#cita-submit').click();await expect(page.getByRole('dialog')).toContainText('Antes');await expect(page.getByRole('dialog')).toContainText('Nuevo horario');await page.route('**/appointments/'+created.id+'/reprogramar',r=>r.fulfill({status:500,contentType:'application/json',body:'{"error":"No se pudo cambiar"}'}));await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-modal-error')).toContainText('No se pudo cambiar');assert.equal((await get(tutor,created.id)).fechaHoraSolicitada,slots[8].inicio);await page.unroute('**/appointments/'+created.id+'/reprogramar');await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-state')).toContainText('Pendiente');await page.reload();await expect(page.locator('.main')).toContainText('Cita reprogramada');await page.locator('[data-appointment-action=cancelar]').click();await page.locator('#appointment-motive').fill('Cambio de planes');await page.keyboard.press('Escape');await expect(page.locator('[data-appointment-action=cancelar]')).toBeFocused();await page.locator('[data-appointment-action=cancelar]').click();await page.locator('#appointment-motive').fill('Cambio de planes');await page.locator('#mod-confirm').click();await expect(page.locator('.appointment-state')).toContainText('Cancelada');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);assert.deepEqual(errors,[]);
  });
  await t.test('otro personal decide y deshabilita modal obsoleto sin borrar motivo',async()=>{
   const created=(await(await post(tutor,slots[10])).json()).appointment;const {page,errors}=await pageFor('u003');await go(page,'#/app/citas/'+created.id+'/detalle');await page.locator('[data-appointment-action=rechazar]').click();await page.locator('#appointment-motive').fill('Motivo aún sin enviar');await act(staff,created,'aceptar');await expect(page.locator('#appointment-update')).toContainText('cambió');await expect(page.locator('#mod-confirm')).toBeDisabled();await expect(page.locator('#appointment-motive')).toHaveValue('Motivo aún sin enviar');await page.locator('#mod-cancel').click();await page.locator('#appointment-detail-refresh').click();await expect(page.locator('.appointment-state')).toContainText('Aceptada');assert.deepEqual(errors,[]);
  });
  await t.test('fase 5 completa: wizard, rechazo/corrección documental, aceptación, cita y gestión',async()=>{
   const owner=await pageFor('u002'),worker=await pageFor('u003');const p=owner.page,w=worker.page;
   await go(p,'#/app/inscripciones/nueva?inst=i001');await p.locator('#student-sel').selectOption('new');await p.locator('[name=new_nombre]').fill('Aspirante cierre fase cinco');await p.locator('[name=new_fecha]').fill('2015-01-01');await p.locator('#step-form button[type=submit]').click();await expect(p.locator('[name=tutorCedula]')).toHaveValue(db.users.find(u=>u.id==='u002').cedula);await p.locator('[name=tutorCedula]').fill('00198765432');await p.locator('[name=tutorPhone]').fill('8095550123');await p.locator('#step-form button[type=submit]').click();await p.locator('[name=gradoSolicitado]').selectOption('1ro de Primaria');await p.locator('[name=cicloEscolar]').selectOption('2026-2027');await p.locator('#btn-next-3').click();await p.locator('#file-0').setInputFiles({name:'acta.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nacta\n%%EOF')});await expect(p.locator('.remove-doc-btn')).toBeVisible();await p.locator('#btn-next-4').click();const submitted=p.waitForResponse(r=>r.url().endsWith('/api/enrollments')&&r.request().method()==='POST');await p.locator('#btn-submit-final').click();const enrollment=(await(await submitted).json()).enrollment;assert.equal(enrollment.contactoTutor.cedula,'00198765432');assert.equal(JSON.parse(fs.readFileSync(dbp)).users.find(u=>u.id==='u002').cedula,db.users.find(u=>u.id==='u002').cedula);
   await go(w,'#/app/inscripciones/'+enrollment.id+'/detalle');await w.locator('[data-enrollment-action=revisar]').click();await w.locator('#mod-confirm').click();await expect(w.locator('.enrollment-state')).toContainText('En revisión');await w.getByRole('button',{name:'Abrir documentos',exact:true}).click();await w.locator('.doc-reject-btn').click();await w.locator('#rechazo-motivo').fill('Necesitamos una copia legible');await w.locator('#mod-confirm').click();await expect(w.locator('.main')).toContainText('Necesitamos una copia legible');
   await go(p,'#/app/inscripciones/'+enrollment.id+'/detalle');await p.getByRole('button',{name:'Corregir documentos',exact:true}).click();await p.locator('#file-0').setInputFiles({name:'acta-corregida.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\ncorregida\n%%EOF')});await expect(p.locator('#btn-submit-corrections')).toBeEnabled();await p.locator('#btn-submit-corrections').click();await p.locator('#mod-confirm').click();await expect(p.locator('#btn-submit-corrections')).toHaveCount(0);
   await go(w,'#/app/inscripciones/'+enrollment.id+'/detalle');await expect(w.locator('.enrollment-state')).toContainText('En revisión');await w.getByRole('button',{name:'Abrir documentos',exact:true}).click();await w.locator('.doc-accept-btn').click();await w.locator('#mod-confirm').click();await expect(w.locator('.main')).toContainText('Aprobado');await go(w,'#/app/inscripciones/'+enrollment.id+'/detalle');await w.locator('[data-enrollment-action=aceptar]').click();await w.locator('#mod-confirm').click();await expect(w.locator('.enrollment-state')).toContainText('Aceptada');
   const capacity=JSON.parse(fs.readFileSync(dbp)).enrollmentCapacities;await go(p,'#/app/inscripciones/'+enrollment.id+'/detalle');await expect(p.locator('.enrollment-state')).toContainText('Aceptada');await p.getByRole('button',{name:'Solicitar cita',exact:true}).click();await expect(p.locator('#cita-enrollment')).toHaveValue(enrollment.id);await p.locator('#cita-month').fill(month);await p.locator(`[name=slotId][value="${slots[11].id}"]`).check();await p.locator('#cita-submit').click();await expect(p.getByRole('dialog')).toContainText(enrollment.id);const booked=p.waitForResponse(r=>r.url().endsWith('/api/appointments')&&r.request().method()==='POST');await p.locator('#mod-confirm').click();const appointment=(await(await booked).json()).appointment;await expect(p.locator('.appointment-state')).toContainText('Pendiente');assert.equal(appointment.enrollmentId,enrollment.id);
   await go(w,'#/app/citas/'+appointment.id+'/detalle');await w.locator('[data-appointment-action=aceptar]').click();await w.locator('#mod-confirm').click();await expect(w.locator('.appointment-state')).toContainText('Aceptada');await p.reload();await expect(p.locator('.appointment-state')).toContainText('Aceptada');await p.locator('[data-appointment-action=reprogramar]').click();await p.locator(`[name=slotId][value="${slots[12].id}"]`).check();await p.locator('#cita-submit').click();await p.locator('#mod-confirm').click();await expect(p.locator('.appointment-state')).toContainText('Pendiente');await p.locator('[data-appointment-action=cancelar]').click();await p.locator('#mod-confirm').click();await expect(p.locator('.appointment-state')).toContainText('Cancelada');assert.deepEqual(JSON.parse(fs.readFileSync(dbp)).enrollmentCapacities,capacity);assert.equal((await(await tutor.get('/api/enrollments/'+enrollment.id)).json()).enrollment.estado,'Aceptada');
   if(process.env.F55_SCREENSHOTS){fs.mkdirSync(process.env.F55_SCREENSHOTS,{recursive:true});await p.screenshot({path:path.join(process.env.F55_SCREENSHOTS,'fase5-cita-cancelada.png'),fullPage:true,animations:'disabled'});await go(p,`#/app/instituciones/i001/calendario?mes=${month}`);await p.locator('.appointment-available-list').first().waitFor();await p.screenshot({path:path.join(process.env.F55_SCREENSHOTS,'calendario-disponibilidad.png'),fullPage:true,animations:'disabled'});}
   assert.deepEqual(owner.errors,[]);assert.deepEqual(worker.errors,[]);
  });

 }finally{if(browser)await browser.close();for(const c of contexts)await(c.dispose?c.dispose():c.close());const done=once(server,'exit');server.kill();if(server.exitCode===null&&server.signalCode===null)await done;for(const [f,bytes]of protectedFiles)if(bytes)assert.deepEqual(fs.readFileSync(path.join(root,f)),bytes);fs.rmSync(dir,{recursive:true,force:true});}
});
