const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('fs'),path=require('path'),os=require('os');const {spawn}=require('child_process'),{once}=require('events');
const {chromium,request,expect}=require('playwright/test');const bcrypt=require('bcryptjs');const {randomUUID}=require('crypto');
test('F5.5: citas y cierre integrado de fase 5',{timeout:240000},async t=>{
 const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'inscolar-f55-'));const protectedFiles=['data/db.json','test_puppeteer.js'].map(f=>[f,fs.existsSync(path.join(root,f))?fs.readFileSync(path.join(root,f)):null]);
 for(const f of ['server.js','routes','lib','public'])fs.cpSync(path.join(root,f),path.join(dir,f),{recursive:true});fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'dir');fs.mkdirSync(path.join(dir,'data'));
 const dbp=path.join(dir,'data/db.json'),db=JSON.parse(fs.readFileSync(path.join(root,'data/db.json'))),password='F55Test#2026';for(const u of db.users)Object.assign(u,{passwordHash:bcrypt.hashSync(password,4),estado:'Activo',mustChangePassword:false,mfaEnabled:false});
 db.appointments=[];db.appointmentSlots=[];db.drafts=[];db.enrollments=[];db.documents=[];db.notifications=[];db.logs=[];db.enrollmentReservations=[];db.enrollmentCapacities=[{id:'ecf55',institucionId:'i001',cicloEscolar:'2026-2027',grado:'1ro de Primaria',limite:20}];
 const date=require('../lib/appointment-service').dateKey(new Date(Date.now()+7*86400000));const month=date.slice(0,7);
 db.periods=[{id:'f55period',institucionId:'i001',cicloEscolar:'2026-2027',inscripcion:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString()},documentos:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString()},citas:{desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+60*86400000).toISOString(),limiteCitas:50},documentosRequeridos:[{nombre:'Acta F55',niveles:['Primaria'],formatos:['PDF'],maxMb:1}]}];
 fs.writeFileSync(dbp,JSON.stringify(db));fs.writeFileSync(path.join(dir,'fail.cjs'),"const fs=require('fs'),path=require('path'),rename=fs.renameSync;fs.renameSync=(a,b)=>{if(fs.existsSync(path.join(__dirname,'FAIL_SAVE')))throw Error('fallo inyectado');return rename(a,b);};");
 const sock=require('net').createServer();sock.listen(0,'127.0.0.1');await once(sock,'listening');const port=sock.address().port;await new Promise(r=>sock.close(r));const base=`http://127.0.0.1:${port}`;
 const server=spawn(process.execPath,['--require',path.join(dir,'fail.cjs'),'server.js'],{cwd:dir,env:{...process.env,PORT:String(port),DB_PATH:dbp},stdio:['ignore','pipe','pipe']});const contexts=[];let browser;
 try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',x=>{if(String(x).includes('corriendo en'))resolve()});server.once('error',reject);server.stderr.on('data',x=>reject(Error(String(x))));});
  async function login(id){const c=await request.newContext({baseURL:base});contexts.push(c);assert.equal((await c.post('/api/auth/login',{data:{email:db.users.find(u=>u.id===id).email,password}})).status(),200);return c;}
  const tutor=await login('u002'),tutor2=await login('u008'),staff=await login('u003'),other=await login('u005'),admin=await login('u001'),support=await login('u004');
  const avail=async(c=tutor,extra='')=>(await(await c.get(`/api/appointments/availability?institucionId=i001&mes=${month}${extra}`)).json()).slots;
  const get=async(c,id)=>(await(await c.get('/api/appointments/'+id)).json()).appointment;
  const post=(c,slot,extra={})=>c.post('/api/appointments',{data:{institucionId:'i001',motivo:'Entrevista de admisión',slotId:slot.id,requestId:randomUUID(),...extra}});
  const act=async(c,a,action,extra={})=>c.post(`/api/appointments/${a.id}/${action}`,{data:{version:(await get(c,a.id)).version,...extra}});
  let slots,a;
  await t.test('horarios explícitos, permisos y periodo; no inventa horarios',async()=>{assert.deepEqual(await avail(),[]);const data={periodId:'f55period',fecha:date,desde:'09:00',hasta:'17:00',duracionMinutos:30,capacidad:1};assert.equal((await other.post('/api/institutions/i001/appointment-slots',{data})).status(),403);assert.equal((await tutor.post('/api/institutions/i001/appointment-slots',{data})).status(),403);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data:{...data,fecha:'2020-01-01'}})).status(),400);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data})).status(),200);assert.equal((await staff.post('/api/institutions/i001/appointment-slots',{data})).status(),409);slots=await avail();assert.equal(slots.length,16);assert.ok(slots.every(s=>s.disponibles===1&&s.fecha===date&&s.inicio.endsWith('Z')));});
  await t.test('rechaza fechas arbitrarias, pasadas y estudiantes ajenos',async()=>{assert.equal((await post(tutor,{id:'arbitraria'},{fechaHoraSolicitada:'2090-01-01T12:00:00Z'})).status(),400);const alien=db.students.find(s=>s.tutorId!=='u002');assert.equal((await post(tutor,slots[0],{studentId:alien.id})).status(),403);assert.equal((await other.get(`/api/appointments/availability?institucionId=i001&mes=${month}`)).status(),403);});
  await t.test('crear Pendiente ocupa un lugar; reintento no duplica ni notifica dos veces',async()=>{const requestId=randomUUID();const r=await post(tutor,slots[0],{requestId});assert.equal(r.status(),200);a=(await r.json()).appointment;assert.equal(a.estado,'Pendiente');assert.ok(!(await avail()).some(s=>s.id===slots[0].id));const replay=await post(tutor,slots[0],{requestId});assert.equal(replay.status(),200);assert.equal((await replay.json()).appointment.id,a.id);assert.equal((await post(tutor,slots[1],{requestId})).status(),409);const data=JSON.parse(fs.readFileSync(dbp));assert.equal(data.appointments.length,1);assert.equal(data.notifications.filter(n=>n.entityId===a.id).length,1);assert.ok(data.notifications[0].url.includes('/citas/'));});
  await t.test('aceptar mantiene capacidad; versiones y roles bloquean decisiones obsoletas',async()=>{assert.equal((await act(tutor,a,'aceptar')).status(),403);assert.equal((await admin.get('/api/appointments')).status(),403);assert.equal((await support.get('/api/appointments')).status(),403);assert.equal((await other.post(`/api/appointments/${a.id}/aceptar`,{data:{version:0}})).status(),403);assert.equal((await act(staff,a,'aceptar')).status(),200);assert.equal((await get(tutor,a.id)).estado,'Aceptada');assert.ok(!(await avail()).some(s=>s.id===slots[0].id));assert.equal((await staff.post(`/api/appointments/${a.id}/rechazar`,{data:{version:0,motivo:'Decisión anterior'}})).status(),409);});
  await t.test('último lugar entre dos clientes y dobles clics no sobrevende',async()=>{const responses=await Promise.all([post(tutor,slots[1]),post(tutor2,slots[1])]);assert.deepEqual(responses.map(r=>r.status()).sort(),[200,409]);const key=randomUUID();const double=await Promise.all([post(tutor,slots[2],{requestId:key}),post(tutor,slots[2],{requestId:key})]);assert.deepEqual(double.map(r=>r.status()),[200,200]);assert.equal((await double[0].json()).appointment.id,(await double[1].json()).appointment.id);});
  await t.test('reprogramación fallida conserva estado y horario; éxito vuelve a Pendiente',async()=>{const before=await get(tutor,a.id);assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[1].id})).status(),409);assert.deepEqual(await get(tutor,a.id),before);fs.writeFileSync(path.join(dir,'FAIL_SAVE'),'1');try{assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[3].id})).status(),500);assert.deepEqual(await get(tutor,a.id),before);}finally{fs.unlinkSync(path.join(dir,'FAIL_SAVE'));}assert.equal((await act(tutor,a,'reprogramar',{slotId:slots[3].id})).status(),200);const after=await get(tutor,a.id);assert.equal(after.estado,'Pendiente');assert.equal(after.fechaHoraSolicitada,slots[3].inicio);assert.ok((await avail()).some(s=>s.id===slots[0].id));assert.ok(!(await avail()).some(s=>s.id===slots[3].id));assert.equal(after.historial.filter(h=>h.accion==='Cita reprogramada').length,1);});
  await t.test('rechazar requiere motivo y libera una sola vez con aviso visible',async()=>{assert.equal((await act(staff,a,'rechazar',{motivo:' '})).status(),400);assert.equal((await act(staff,a,'rechazar',{motivo:'No podemos atender esa fecha'})).status(),200);assert.equal((await act(staff,a,'rechazar',{motivo:'Reintento'})).status(),409);assert.ok((await avail()).some(s=>s.id===slots[3].id&&s.disponibles===1));assert.equal((await get(tutor,a.id)).motivoRechazo,'No podemos atender esa fecha');});
  await t.test('cancelar Pendiente o Aceptada libera una vez y conserva expediente',async()=>{for(const accepted of [false,true]){const r=await post(tutor,slots[4]);const b=(await r.json()).appointment;if(accepted)assert.equal((await act(staff,b,'aceptar')).status(),200);assert.equal((await tutor2.post('/api/appointments/'+b.id+'/cancelar',{data:{version:0}})).status(),403);assert.equal((await act(staff,b,'cancelar',{motivo:''})).status(),400);assert.equal((await act(tutor,b,'cancelar',{motivo:'Elegí otra fecha'})).status(),200);assert.equal((await act(tutor,b,'cancelar')).status(),409);assert.ok((await avail()).some(s=>s.id===slots[4].id&&s.disponibles===1));assert.equal((await get(tutor,b.id)).motivoCancelacion,'Elegí otra fecha');}});
  await t.test('aislamiento en lista, detalle, calendario y disponibilidad; cupos de inscripción intactos',async()=>{assert.equal((await tutor2.get('/api/appointments/'+a.id)).status(),403);const list=(await(await tutor.get('/api/appointments')).json()).appointments;assert.ok(list.every(a=>a.tutorId==='u002'));assert.equal((await other.get(`/api/institutions/i001/calendar?mes=${month}`)).status(),403);const calendar=await(await tutor2.get(`/api/institutions/i001/calendar?mes=${month}`)).json();assert.ok(Object.values(calendar.dias).flat().every(a=>a.tutorId==='u008'));assert.equal((await tutor2.get(`/api/appointments/availability?institucionId=i001&mes=${month}&excludeId=${a.id}`)).status(),403);assert.deepEqual(JSON.parse(fs.readFileSync(dbp)).enrollmentCapacities,db.enrollmentCapacities);});
  await t.test('vínculo de solicitud valida tutor, estudiante e institución sin exigir aceptación inventada',async()=>{let state=JSON.parse(fs.readFileSync(dbp));state.enrollments.push({id:'f55linked',tutorId:'u002',studentId:db.students.find(s=>s.tutorId==='u002').id,institucionId:'i001',estado:'Enviada',version:0,cicloEscolar:'2026-2027',gradoSolicitado:'1ro de Primaria',createdAt:new Date().toISOString()});fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await post(tutor2,slots[5],{enrollmentId:'f55linked'})).status(),403);assert.equal((await post(staff,slots[5],{enrollmentId:'f55linked'})).status(),200);assert.equal((await post(staff,slots[6])).status(),400);});
  await t.test('paginación, fecha y próximas/anteriores filtran antes de contar',async()=>{const all=await(await tutor.get('/api/appointments')).json();const p1=await(await tutor.get('/api/appointments?page=1&limit=2')).json(),p2=await(await tutor.get('/api/appointments?page=2&limit=2')).json();assert.equal(p1.total,all.total);assert.ok(p1.appointments.every(a=>!p2.appointments.some(b=>a.id===b.id)));const next=await(await tutor.get('/api/appointments?grupo=proximas&fecha='+date)).json();assert.ok(next.appointments.every(a=>['Pendiente','Aceptada'].includes(a.estado)));const old=await(await tutor.get('/api/appointments?grupo=anteriores')).json();assert.ok(old.appointments.every(a=>['Rechazada','Cancelada'].includes(a.estado)));assert.equal((await tutor.get('/api/appointments?page=0')).status(),400);});
  if(process.env.F55_API_ONLY)return;
  browser=await chromium.launch();
  // Se añaden a continuación los recorridos UI sobre este mismo backend aislado.
 }finally{if(browser)await browser.close();for(const c of contexts)await(c.dispose?c.dispose():c.close());const done=once(server,'exit');server.kill();if(server.exitCode===null&&server.signalCode===null)await done;for(const [f,bytes]of protectedFiles)if(bytes)assert.deepEqual(fs.readFileSync(path.join(root,f)),bytes);fs.rmSync(dir,{recursive:true,force:true});}
});
