const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inscolar-audit-'));process.env.DB_PATH=path.join(dir,'db.json');
const {load,save}=require('../lib/db'),{logEvent}=require('../lib/audit'),store=require('../lib/audit-store'),contract=require('../lib/audit-contract');
function fixture(){fs.writeFileSync(process.env.DB_PATH,JSON.stringify({users:[{id:'a',nombre:'Administrador',role:'Administrador',estado:'Activo',passwordHash:'original',notifyByEmail:true}],institutions:[],logs:[],auditOutbox:[],ratings:[],reports:[]}));if(fs.existsSync(store.AUDIT_PATH))fs.unlinkSync(store.AUDIT_PATH);}
test('negocio y bandeja se confirman juntos, old/new seguros, actor y correlación',()=>{fixture();const db=load();Object.defineProperty(db,'_auditContext',{value:{actor:db.users[0],correlationId:'request-1'}});db.users[0].estado='Inactivo';save(db);const e=load().logs[0];assert.equal(e.accion,'Usuario desactivado');assert.equal(e.actorId,'a');assert.equal(e.correlationId,'request-1');assert.equal(e.anterior.estado,'Activo');assert.equal(e.nuevo.estado,'Inactivo');assert.ok(!JSON.stringify(e).includes('original'));assert.equal(store.read().events.length,0);store.flush();assert.equal(store.read().events.length,1);assert.equal(load().auditOutbox[0].status,'Persisted');});
test('fallo de auditoría conserva negocio, limita reintentos, recuperación sin duplicar',()=>{fixture();const db=load();db.ratings.push({id:'r1',institucionId:'i1',estrellas:5});save(db);const writer=()=>{throw Error('password=secret')};for(const now of [100000,102000,105000])store.flush({now,writer});assert.equal(load().ratings[0].estrellas,5);assert.equal(store.status().failed,1);assert.equal(store.read().events.length,0);store.retryFailed();store.flush();store.flush();assert.equal(store.read().events.length,1);assert.equal(store.status().failed,0);assert.ok(!JSON.stringify(load()).includes('secret'));});
test('reintento tras persistencia antes de ack es idempotente; payload contradictorio se rechaza',()=>{fixture();const db=load();logEvent(db,{accion:'Inicio de sesión exitoso',entidad:'Usuario',entidadId:'a',eventId:'same'});save(db);store.append(db.logs[0]);store.flush();assert.equal(store.read().events.length,1);assert.throws(()=>store.append({...db.logs[0],resultado:'Contradictorio'}));});
test('no-op no genera evento; fallo del commit principal no llega al almacén',()=>{fixture();let db=load();logEvent(db,{accion:'Usuario modificado',entidad:'Usuario',entidadId:'a'});save(db);assert.equal(load().logs.length,0);db=load();db.users[0].estado='Inactivo';const rename=fs.renameSync;fs.renameSync=()=>{throw Error('disk')};try{assert.throws(()=>save(db));}finally{fs.renameSync=rename;}store.flush();assert.equal(load().users[0].estado,'Activo');assert.equal(store.read().events.length,0);});
test('privacidad: secretos, archivos y cédula completa; legacy no publica detalle original',()=>{const e=contract.normalize({accion:'Documento rechazado',detalle:'cédula 001-1234567-8 email persona@example.test token=secret',nuevo:{passwordHash:'hash',cedula:'00112345678',archivo:'base64',estado:'Rechazado'},datos:{correo:'p@example.test',storageFile:'file',motivo:'ilegible'}});const json=JSON.stringify(e);for(const secret of ['00112345678','001-1234567-8','persona@example.test','secret','hash','base64'])assert.ok(!json.includes(secret),secret);const legacy=contract.normalize({id:'old',detalle:'secret sin etiqueta 00112345678'},{legacy:true});assert.equal(legacy.anterior,null);assert.ok(!legacy.detalle.includes('secret'));assert.equal(legacy.eventId,contract.normalize({id:'old'},{legacy:true}).eventId);});
test('permisos explícitos; bitácora de acceso separada de negocio',()=>{fixture();assert.equal(contract.enabled({role:'Administrador'}),false);assert.equal(contract.enabled({role:'Administrador',auditEnabled:true}),true);assert.equal(contract.enabled({role:'Auditoría'}),true);for(const role of ['Tutor','Soporte','Personal de institución'])assert.equal(contract.enabled({role,auditEnabled:true}),false);store.recordAccess({id:'audit',role:'Auditoría'},'list',{page:1});assert.equal(store.read().accesses.length,1);assert.equal(load().logs.length,0);});
test('cambios de límite y documentos comparten correlación y valores seguros',()=>{fixture();let db=load();db.periods=[{id:'p1',institucionId:'i1',citas:{limiteCitas:5},documentosRequeridos:['Acta']}];save(db);db=load();Object.defineProperty(db,'_auditContext',{value:{actor:db.users[0],correlationId:'period-request'}});db.periods[0].citas.limiteCitas=7;db.periods[0].documentosRequeridos=['Acta','Notas'];logEvent(db,{accion:'Periodo de ciclo modificado',entidad:'Periodo',entidadId:'p1'});save(db);assert.ok(load().logs.some(e=>e.accion==='Límite de citas modificado'&&e.anterior.limite===5&&e.nuevo.limite===7&&e.correlationId==='period-request'));assert.ok(load().logs.some(e=>e.accion==='Requisitos documentales modificados'));});
test('carga documental del borrador y rechazo conservan vínculo y versión sin archivo',()=>{fixture();let db=load();db.drafts=[{id:'draft',data:{institucionId:'i1'}}];db.documents=[{id:'d1',draftId:'draft',estado:'Pendiente',tipoDocumento:'Acta',storageFile:'private-file'}];save(db);assert.ok(load().logs.some(e=>e.accion==='Documento subido'&&e.entidadId==='d1'&&e.institucionId==='i1'));db=load();db.enrollments=[{id:'e1',institucionId:'i1',version:3,estado:'En revisión'}];db.documents[0].enrollmentId='e1';db.documents[0].estado='Rechazado';db.documents[0].motivoRechazo='Ilegible';save(db);const e=load().logs.find(e=>e.accion==='Documento rechazado');assert.equal(e.datos.enrollmentVersion,3);assert.equal(e.anterior.estado,'Pendiente');assert.equal(e.nuevo.motivoRechazo,'Ilegible');assert.ok(!JSON.stringify(e).includes('private-file'));});
