const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path'),{spawn}=require('child_process'),{once}=require('events');
const {chromium,request,expect}=require('playwright/test'),bcrypt=require('bcryptjs');
test('F8: auditoría real, permisos, filtros, detalle y recuperación',{timeout:90000},async t=>{
 const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'inscolar-f8-browser-'));
 const preserved=['data/db.json','test_puppeteer.js'].map(f=>[f,fs.readFileSync(path.join(root,f))]);
 for(const f of ['server.js','routes','lib','public'])fs.cpSync(path.join(root,f),path.join(dir,f),{recursive:true});fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'dir');fs.mkdirSync(path.join(dir,'data'));
 const dbp=path.join(dir,'data/db.json'),db=JSON.parse(fs.readFileSync(path.join(root,'data/db.json'))),password='Audit#2026';
 db.users.forEach(u=>Object.assign(u,{passwordHash:bcrypt.hashSync(password,4),estado:'Activo',mfaEnabled:false,mustChangePassword:false,auditEnabled:u.id==='u001'}));
 db.users.push({...db.users.find(u=>u.id==='u001'),id:'disabled-admin',email:'audit-disabled@example.test',auditEnabled:false});
 db.logs=Array.from({length:25},(_,i)=>({id:'old'+i,fecha:'2026-10-02T'+(i%2?'03:59:59':'04:00:00')+'Z',actorId:null,actorNombre:'Sistema',actorRole:'Sistema',accion:'Cita cancelada',entidad:'Cita',entidadId:'c'+i,detalle:'secret original 00112345678'}));
 db.auditOutbox=[];db.emailOutbox=[];db.notifications=[];db.ratings=[];db.reports=[];
 db.appointments.push({id:'auditaccepted',tutorId:'u002',institucionId:'i001',estado:'Aceptada'});fs.writeFileSync(dbp,JSON.stringify(db));
 const sock=require('net').createServer();sock.listen(0,'127.0.0.1');await once(sock,'listening');const port=sock.address().port;await new Promise(r=>sock.close(r));const base=`http://127.0.0.1:${port}`;
 const server=spawn(process.execPath,['server.js'],{cwd:dir,env:{...process.env,PORT:String(port),DB_PATH:dbp,AUDIT_PATH:dbp+'.audit.json',AUDIT_ADMIN_IDS:'',SMTP_HOST:'',SMTP_PORT:'',SMTP_USER:'',SMTP_PASS:''},stdio:['ignore','pipe','pipe']});let browser;const contexts=[];
 try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',x=>{if(String(x).includes('corriendo en'))resolve()});server.once('error',reject);server.once('exit',c=>reject(Error('Servidor terminó '+c)));});
  async function login(id){const c=await request.newContext({baseURL:base});contexts.push(c);assert.equal((await c.post('/api/auth/login',{data:{email:db.users.find(u=>u.id===id).email,password}})).status(),200);return c;}
  const admin=await login('u001'),auditor=await login('u007'),tutor=await login('u002');
  await t.test('solo auditor o administrador habilitado; detalle también protegido',async()=>{for(const id of ['u004','u003','u002','disabled-admin']){const c=await login(id);assert.equal((await c.get('/api/logs')).status(),403);assert.equal((await c.get('/api/logs/unknown')).status(),403);}assert.equal((await auditor.get('/api/logs')).status(),200);});
  await t.test('paginación y filtros combinados antes del contador; UTC-04 inclusivo',async()=>{const p1=await(await admin.get('/api/logs?actorId=Sistema&accion=Cita%20cancelada')).json(),p2=await(await admin.get('/api/logs?actorId=Sistema&accion=Cita%20cancelada&page=2')).json();assert.equal(p1.total,25);assert.equal(p1.logs.length,20);assert.equal(p2.logs.length,5);assert.ok(!p1.logs.some(a=>p2.logs.some(b=>a.eventId===b.eventId)));const bounds=await(await admin.get('/api/logs?actorId=Sistema&accion=Cita%20cancelada&desde=2026-10-02&hasta=2026-10-02')).json();assert.equal(bounds.total,13);for(const q of ['page=0','limit=101','desde=2026-02-30','desde=2026-10-03&hasta=2026-10-02','accion=Inventada'])assert.equal((await admin.get('/api/logs?'+q)).status(),400);});
  await t.test('consulta registrada por separado y detalle heredado depurado; no edición/borrado',async()=>{const list=await(await admin.get('/api/logs?actorId=Sistema')).json(),id=list.logs[0].eventId;const detail=await(await admin.get('/api/logs/'+encodeURIComponent(id))).json();assert.ok(!JSON.stringify(detail).includes('secret original'));assert.ok(!JSON.stringify(detail).includes('00112345678'));assert.equal((await admin.delete('/api/logs/'+encodeURIComponent(id))).status(),404);assert.equal((await admin.put('/api/logs/'+encodeURIComponent(id),{data:{detalle:'edit'}})).status(),404);const store=JSON.parse(fs.readFileSync(dbp+'.audit.json'));assert.ok(store.accesses.some(a=>a.actorId==='u001'&&a.operation==='detail'));assert.ok(!store.events.some(e=>e.accion==='Consulta de auditoría'));});
  await t.test('calificación, reporte, moderación y contraseña generan eventos persistidos',async()=>{assert.equal((await tutor.post('/api/institutions/i001/ratings',{data:{estrellas:4,comentario:'prueba de auditoría'}})).status(),200);assert.equal((await tutor.post('/api/institutions/i001/ratings',{data:{estrellas:5}})).status(),200);const r=await tutor.post('/api/institutions/i001/reports',{data:{motivo:'Información incorrecta',descripcion:'La dirección necesita corregirse.'}});assert.equal(r.status(),200);const id=(await r.json()).report.id;assert.equal((await admin.put('/api/reports/'+id+'/estado',{data:{estado:'Publicado'}})).status(),200);assert.equal((await tutor.post('/api/users/me/password',{data:{currentPassword:password,newPassword:'AuditNew#2026',confirmNewPassword:'AuditNew#2026'}})).status(),200);await expect.poll(async()=>{const list=await(await admin.get('/api/logs?limit=100')).json();return ['Calificación registrada','Calificación modificada','Reporte enviado','Reporte moderado','Contraseña cambiada'].every(a=>list.logs?.some(e=>e.accion===a));}).toBe(true);const contents=fs.readFileSync(dbp+'.audit.json','utf8');assert.ok(!contents.includes('AuditNew#2026'));assert.ok(!contents.includes('passwordHash'));});
  await t.test('validación de usuario inválido no altera negocio ni genera éxito',async()=>{const before=JSON.parse(fs.readFileSync(dbp)).users.find(u=>u.id==='u003');assert.equal((await admin.put('/api/users/u003',{data:{email:'invalid'}})).status(),400);const after=JSON.parse(fs.readFileSync(dbp)).users.find(u=>u.id==='u003');assert.deepEqual(after,before);});
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({storageState:await admin.storageState(),viewport:{width:375,height:812},colorScheme:'dark'});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await t.test('visor móvil/teclado, filtros, página, detalle y cierre devuelven foco',async()=>{await page.goto(base+'/#/app/auditoria?actorId=Sistema&accion=Cita%20cancelada');await expect(page.locator('#audit-next')).toBeEnabled();await page.locator('#audit-next').focus();await page.keyboard.press('Enter');await expect(page.locator('.table-footer')).toContainText('Página 2 de 2');const button=page.locator('[data-audit-detail]').first();await button.click();await expect(page.locator('#audit-detail section')).toBeFocused();await page.locator('#audit-detail-close').click();await expect(button).toBeFocused();await page.locator('[name=desde]').fill('2026-10-02');await page.locator('[name=hasta]').fill('2026-10-02');await page.getByRole('button',{name:'Aplicar filtros'}).click();await expect(page.locator('.table-footer')).toContainText('de 13');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(dir,'audit-mobile.png')});});
  await t.test('error del almacén ofrece reintento sin presentar cero como éxito',async()=>{const file=dbp+'.audit.json',bytes=fs.readFileSync(file);fs.writeFileSync(file,'invalid json');try{assert.equal((await admin.get('/api/logs')).status(),503);await page.locator('#audit-refresh').click();await expect(page.locator('#audit-retry')).toBeVisible();}finally{fs.writeFileSync(file,bytes);}await page.locator('#audit-retry').click();await expect(page.locator('#audit-filters')).toBeVisible();assert.deepEqual(errors,[]);});
  console.log('F8 navegador: '+dir);
 }finally{if(browser)await browser.close();for(const c of contexts)await c.dispose();server.kill();await once(server,'exit');for(const [f,b] of preserved)assert.deepEqual(fs.readFileSync(path.join(root,f)),b);}
});
