const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const {chromium,request,expect}=require('playwright/test');
const bcrypt=require('bcryptjs');

test('F5.4: servicio y recorridos reales de inscripción', {timeout:180000},async t=>{
 const root=path.resolve(__dirname,'..'),source=process.env.INSCOLAR_TEST_SOURCE || root;
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inscolar-f54-'));
 for(const name of ['server.js','routes','lib','public'])fs.cpSync(path.join(source,name),path.join(dir,name),{recursive:true});
 fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'dir');fs.mkdirSync(path.join(dir,'data'));
 const dbp=path.join(dir,'data/db.json'), db=JSON.parse(fs.readFileSync(path.join(root,'data/db.json'))), password='F54Test#2026';
 const protectedFiles=['data/db.json','test_puppeteer.js'].map(f=>[f,fs.existsSync(path.join(root,f))?fs.readFileSync(path.join(root,f)):null]);
 db.users.forEach(u=>Object.assign(u,{passwordHash:bcrypt.hashSync(password,4),estado:'Activo',mfaEnabled:false,mustChangePassword:false,notifyByEmail:false}));
 db.enrollments=[];db.documents=[];db.drafts=[];db.notifications=[];db.logs=[];db.enrollmentReservations=[];db.enrollmentCapacities=[];
 db.periods=[{id:'f54period',institucionId:'i001',cicloEscolar:'2026-2027',inscripcion:{desde:'2026-01-01T00:00:00Z',hasta:'2027-12-31T00:00:00Z'},documentos:{desde:'2026-01-01T00:00:00Z',hasta:'2027-12-31T00:00:00Z'},documentosRequeridos:[{nombre:'Acta requerida',niveles:['Primaria'],formatos:['PDF'],maxMb:1}]}];
 const student={id:'f54student',tutorId:'u002',nombre:'Aspirante F54',fechaNacimiento:'2015-01-01'};db.students.push(student);
 const initial={id:'f54initial',studentId:student.id,tutorId:'u002',institucionId:'i001',gradoSolicitado:'1ro de Primaria',cicloEscolar:'2026-2027',estado:'Enviada',version:0,createdAt:'2026-10-01T10:00:00Z',requisitosSnapshot:[{tipo:'Acta requerida',formatos:['PDF'],maxSizeMB:1}],requisitosNormalizados:true};
 db.enrollments.push(initial);
 for(let i=0;i<23;i++)db.enrollments.push({...initial,id:'f54page'+String(i).padStart(2,'0'),studentId:'f54student',gradoSolicitado:i%2?'2do de Primaria':'1ro de Primaria',createdAt:`2026-10-01T10:${String(i).padStart(2,'0')}:00Z`});
 db.enrollments.push({...initial,id:'f54foreign',tutorId:'u008',institucionId:'i002'});
 fs.writeFileSync(dbp,JSON.stringify(db));
 const sock=require('node:net').createServer();sock.listen(0,'127.0.0.1');await once(sock,'listening');const port=sock.address().port;await new Promise(r=>sock.close(r));
 fs.writeFileSync(path.join(dir,'fail-save.cjs'),"const fs=require('fs'),path=require('path');const rename=fs.renameSync;fs.renameSync=(a,b)=>{if(fs.existsSync(path.join(__dirname,'FAIL_SAVE')))throw Error('fallo de guardado inyectado');return rename(a,b);};");
 const server=spawn(process.execPath,['--require',path.join(dir,'fail-save.cjs'),'server.js'],{cwd:dir,env:{...process.env,PORT:String(port),DB_PATH:dbp},stdio:['ignore','pipe','pipe']});
 let browser;const contexts=[];const base=`http://127.0.0.1:${port}`;
 try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',c=>{if(String(c).includes('corriendo en'))resolve()});server.stderr.on('data',c=>reject(Error(String(c))));server.once('error',reject);});
  async function login(id){const c=await request.newContext({baseURL:base});contexts.push(c);const u=db.users.find(u=>u.id===id);assert.equal((await c.post('/api/auth/login',{data:{email:u.email,password}})).status(),200);return c;}
  const tutor=await login('u002'),staff=await login('u003'),other=await login('u005'),admin=await login('u001'),support=await login('u004');
  const get=async(c,id)=>(await(await c.get('/api/enrollments/'+id)).json()).enrollment;
  const mutate=async(c,id,action,extra={},v)=>c.post('/api/enrollments/'+id+'/'+action,{data:{version:v===undefined?(await get(c,id)).version:v,...extra}});
  const configure=limite=>staff.put('/api/institutions/i001/periods/f54period/cupos-inscripcion',{data:{grado:'1ro de Primaria',limite}});
  function fixture(id,fields={},docs=false){const state=JSON.parse(fs.readFileSync(dbp));state.enrollments.push({...initial,id,...fields});if(docs)state.documents.push({id:'doc-'+id,enrollmentId:id,tipoDocumento:'Acta requerida',estado:'Aceptado',uploadedAt:new Date().toISOString(),tutorId:'u002'});fs.writeFileSync(dbp,JSON.stringify(state));}
  await t.test('API anterior no permite aceptar sin revisión ni documentos',async()=>{
   const r=await staff.post('/api/enrollments/f54initial/decidir',{data:{estado:'Aprobada',version:0}});
   assert.notEqual(r.status(),200,'La API legacy aceptó la inscripción sin revisión ni documentos obligatorios');
  });
  if(process.env.F54_BASELINE_ONLY)return;
  await t.test('aislamiento de tutor, personal e institución ajena',async()=>{for(const [c,field,value] of [[tutor,'tutorId','u002'],[staff,'institucionId','i001']]){const r=await(await c.get('/api/enrollments')).json();assert.ok(r.enrollments.every(e=>e[field]===value));}assert.equal((await other.get('/api/enrollments/f54initial')).status(),403);assert.equal((await tutor.get('/api/enrollments/f54foreign')).status(),403);assert.equal((await mutate(other,'f54initial','revisar',{},0)).status(),403);assert.equal((await mutate(tutor,'f54initial','revisar')).status(),403);});
  await t.test('paginación real y contadores filtrados',async()=>{const a=await(await tutor.get('/api/enrollments?page=1&limit=10')).json(),b=await(await tutor.get('/api/enrollments?page=2&limit=10')).json();assert.equal(a.total,24);assert.equal(a.enrollments.length,10);assert.ok(a.enrollments.every(x=>!b.enrollments.some(y=>x.id===y.id)));const r=await(await staff.get('/api/enrollments?grado=2do%20de%20Primaria&q=Aspirante&page=1&limit=5')).json();assert.equal(r.total,11);assert.equal(r.enrollments.length,5);assert.equal((await staff.get('/api/enrollments?page=0&limit=10')).status(),400);});
  await t.test('inicio de revisión, versión y documentos obligatorios',async()=>{assert.equal((await mutate(staff,'f54initial','decidir',{estado:'Aceptada'})).status(),409);assert.equal((await mutate(staff,'f54initial','revisar')).status(),200);assert.equal((await get(tutor,'f54initial')).estado,'En revisión');assert.equal((await mutate(staff,'f54initial','decidir',{estado:'Aceptada'})).status(),422);assert.equal((await mutate(staff,'f54initial','decidir',{estado:'Aprobada'})).status(),400);});
  await t.test('rechazo exige motivo, es terminal, conserva historial y notificación',async()=>{assert.equal((await mutate(staff,'f54initial','decidir',{estado:'Rechazada',motivo:' '})).status(),400);assert.equal((await mutate(staff,'f54initial','decidir',{estado:'Rechazada',motivo:'No cumple el requisito de edad'})).status(),200);const r=await(await tutor.get('/api/enrollments/f54initial')).json();assert.equal(r.enrollment.motivoRechazo,'No cumple el requisito de edad');assert.equal(r.historial.length,2);assert.equal((await mutate(staff,'f54initial','revisar')).status(),409);assert.equal((await mutate(tutor,'f54initial','cancelar')).status(),409);const n=await(await tutor.get('/api/notifications')).json();assert.ok(n.notifications.some(n=>n.entityId==='f54initial' && n.nuevo==='Rechazada' && n.url.includes('/detalle')));});
  await t.test('falta de configuración de cupos bloquea aceptación',async()=>{fixture('capacity-missing',{estado:'En revisión'},true);assert.equal((await mutate(staff,'capacity-missing','decidir',{estado:'Aceptada'})).status(),422);assert.equal((await other.put('/api/institutions/i001/periods/f54period/cupos-inscripcion',{data:{grado:'1ro de Primaria',limite:1}})).status(),403);assert.equal((await configure(1)).status(),200);});
  await t.test('aceptación consume una vez; dos solicitudes no exceden el cupo',async()=>{fixture('capacity-race',{estado:'En revisión'},true);const responses=await Promise.all([mutate(staff,'capacity-missing','decidir',{estado:'Aceptada'},0),mutate(admin,'capacity-race','decidir',{estado:'Aceptada'},0)]);assert.deepEqual(responses.map(r=>r.status()).sort(),[200,409]);assert.equal((await mutate(staff,'capacity-missing','decidir',{estado:'Aceptada'},0)).status(),409);const c=(await get(staff,'capacity-missing')).disponibilidad;assert.equal(c.ocupados,1);assert.equal(c.disponibles,0);});
  await t.test('reserva propia se convierte sin descontar dos veces; rechazos liberan solo la suya',async()=>{assert.equal((await configure(3)).status(),200);fixture('reserved',{estado:'En revisión'},true);fixture('reject-reserved');let state=JSON.parse(fs.readFileSync(dbp));const capacity=state.enrollmentCapacities[0];state.enrollmentReservations.push({id:'r-own',capacityId:capacity.id,enrollmentId:'reserved',estado:'Reservada'},{id:'r-reject',capacityId:capacity.id,enrollmentId:'reject-reserved',estado:'Reservada'});fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await mutate(staff,'reserved','decidir',{estado:'Aceptada'})).status(),200);assert.equal((await mutate(staff,'reject-reserved','decidir',{estado:'Rechazada',motivo:'No corresponde este grado'})).status(),200);assert.equal((await mutate(staff,'reject-reserved','decidir',{estado:'Rechazada',motivo:'Reintento'},0)).status(),409);state=JSON.parse(fs.readFileSync(dbp));assert.equal(state.enrollmentReservations.find(r=>r.id==='r-own').estado,'Consumida');assert.equal(state.enrollmentReservations.find(r=>r.id==='r-reject').estado,'Liberada');assert.equal((await get(staff,'reserved')).disponibilidad.ocupados,2);assert.equal((await get(staff,'reserved')).disponibilidad.disponibles,1);assert.equal((await configure(1)).status(),409);});
  await t.test('cancelación conserva expediente y libera reserva una sola vez',async()=>{fixture('cancel-reserved');let state=JSON.parse(fs.readFileSync(dbp));state.enrollmentReservations.push({id:'r-cancel',capacityId:state.enrollmentCapacities[0].id,enrollmentId:'cancel-reserved',estado:'Reservada'});fs.writeFileSync(dbp,JSON.stringify(state));assert.equal((await mutate(staff,'cancel-reserved','cancelar')).status(),403);assert.equal((await mutate(tutor,'cancel-reserved','cancelar',{motivo:'Elegimos otra institución'})).status(),200);assert.equal((await get(tutor,'cancel-reserved')).estado,'Cancelada');assert.equal((await mutate(tutor,'cancel-reserved','cancelar',{},0)).status(),409);state=JSON.parse(fs.readFileSync(dbp));assert.equal(state.enrollmentReservations.find(r=>r.id==='r-cancel').estado,'Liberada');assert.equal(state.enrollments.find(e=>e.id==='cancel-reserved').historial.length,1);});
  await t.test('decisiones contradictorias de dos sesiones y solicitudes obsoletas se bloquean',async()=>{fixture('stale');const old=await get(staff,'stale');assert.equal((await mutate(admin,'stale','revisar',{},old.version)).status(),200);assert.equal((await mutate(staff,'stale','decidir',{estado:'Rechazada',motivo:'Revisión obsoleta'},old.version)).status(),409);const r=await Promise.all([mutate(staff,'stale','decidir',{estado:'Rechazada',motivo:'No corresponde'},1),mutate(admin,'stale','decidir',{estado:'Rechazada',motivo:'Otra decisión'},1)]);assert.deepEqual(r.map(r=>r.status()).sort(),[200,409]);});
  await t.test('periodo y grado válidos y permiso de Soporte existente',async()=>{fixture('bad-period',{estado:'En revisión',createdAt:'2025-01-01T00:00:00Z'},true);assert.equal((await mutate(staff,'bad-period','decidir',{estado:'Aceptada'})).status(),422);fixture('bad-grade',{estado:'En revisión',gradoSolicitado:'Inventado'},true);assert.equal((await mutate(staff,'bad-grade','decidir',{estado:'Aceptada'})).status(),422);fixture('support-review');assert.equal((await mutate(support,'support-review','revisar')).status(),200);});
  await t.test('fallo de guardado no persiste estado, cupo, historial ni notificación',async()=>{
   fixture('save-failure');const before=fs.readFileSync(dbp);fs.writeFileSync(path.join(dir,'FAIL_SAVE'),'1');
   try {assert.equal((await mutate(staff,'save-failure','revisar')).status(),500);assert.deepEqual(fs.readFileSync(dbp),before);assert.equal(fs.readdirSync(path.join(dir,'data')).filter(f=>f.endsWith('.tmp')).length,0);}finally{fs.unlinkSync(path.join(dir,'FAIL_SAVE'));}
   assert.equal((await mutate(staff,'save-failure','revisar')).status(),200);assert.equal((await get(staff,'save-failure')).estado,'En revisión');
  });
  browser=await chromium.launch();
  async function pageFor(id,options={}){const c=await browser.newContext(options);contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(7000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const u=db.users.find(u=>u.id===id);await p.goto(base+'/#/login');await p.locator('[name=email]').fill(u.email);await p.locator('[name=password]').fill(password);await p.locator('#login-form button[type=submit]').click();await expect(p.locator('.main')).toContainText(u.email);return {page:p,context:c,errors};}
  await t.test('tutor ve rechazo, motivo, historial y listado paginado',async()=>{const {page,errors}=await pageFor('u002');await page.evaluate(()=>location.hash='#/app/inscripciones/f54initial/detalle');await expect(page.locator('.main')).toContainText('No cumple el requisito de edad');await expect(page.locator('.enrollment-history')).toContainText('Inscripción rechazada');assert.equal(await page.locator('[data-enrollment-action]').count(),0);await page.evaluate(()=>location.hash='#/app/inscripciones');await page.locator('#enrollment-next').click();await expect(page.locator('.table-footer')).toContainText('Página 2');assert.deepEqual(errors,[]);});
  await t.test('fallo conserva motivo, teclado y recuperación de rechazo en móvil oscuro',async()=>{fixture('ui-reject');const {page,errors}=await pageFor('u003',{viewport:{width:375,height:812},colorScheme:'dark'});await page.evaluate(()=>location.hash='#/app/inscripciones/ui-reject/detalle');await page.locator('[data-enrollment-action=rechazar]').click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('#enrollment-motive').focus();await page.keyboard.press('Shift+Tab');await expect(page.locator('#mod-confirm')).toBeFocused();await page.keyboard.press('Tab');await expect(page.locator('#enrollment-motive')).toBeFocused();await page.locator('#enrollment-motive').fill('Motivo que debe conservarse');await page.route('**/api/enrollments/ui-reject/decidir',r=>r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Fallo de prueba'})}));await page.locator('#mod-confirm').click();await expect(page.locator('.enrollment-modal-error')).toContainText('Fallo de prueba');await expect(page.locator('#enrollment-motive')).toHaveValue('Motivo que debe conservarse');await expect(page.locator('#mod-confirm')).toBeEnabled();await page.unroute('**/api/enrollments/ui-reject/decidir');await page.locator('#mod-confirm').click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.enrollment-state')).toContainText('Rechazada');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);if(process.env.F54_SCREENSHOTS){fs.mkdirSync(process.env.F54_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.F54_SCREENSHOTS,'personal-rechazo-mobile.png'),fullPage:true,animations:'disabled'});}assert.deepEqual(errors,[]);});
  await t.test('transiciones de apartados sin bloquear controles, movimiento reducido y alta sin NUP',async()=>{
   const {page,errors}=await pageFor('u002',{viewport:{width:375,height:812}});
   await page.addInitScript(()=>{const animate=Element.prototype.animate;Element.prototype.animate=function(...args){if(args[1]?.duration===320&&args[0]?.[0]?.opacity===0.2)window.screenArrivals=(window.screenArrivals||0)+1;return animate.apply(this,args);};});
   await page.reload();await expect(page.locator('.main')).toBeVisible();
   let releaseRequest, requestEntered;
   const gate=new Promise(resolve=>releaseRequest=resolve),entered=new Promise(resolve=>requestEntered=resolve);
   await page.route('**/api/notifications?*',async route=>{requestEntered();await gate;await route.continue();});
   const shell=await page.locator('.topbar').elementHandle();
   try{
    await page.evaluate(()=>location.hash='#/app/manual');await entered;
    await expect(page.locator('.topbar')).toBeVisible();assert.ok(await shell.evaluate(el=>el.isConnected));
    await expect(page.locator('.main .loading-spinner')).toBeVisible();await expect(page.locator('.main [role=status]')).toContainText('Cargando');
    await page.screenshot({path:path.join(dir,'loading-shell-mobile.png'),animations:'disabled'});
   }finally{releaseRequest();await page.unrouteAll({behavior:'wait'});}
   await expect(page.locator('.main .loading')).toHaveCount(0);await expect(page.locator('.main h2')).toBeVisible();
   for(const section of ['seguridad','configuracion','manual','notificaciones','inscripciones','citas','inscripciones/estudiante-nuevo']){
    const count=await page.evaluate(()=>window.screenArrivals||0);await page.evaluate(s=>location.hash='#/app/'+s,section);await expect.poll(()=>page.evaluate(()=>window.screenArrivals||0)).toBeGreaterThan(count);await expect(page.locator('.main')).toBeVisible();assert.ok(await page.locator('.main').evaluate(el=>getComputedStyle(el).pointerEvents!=='none'));
   }
   await expect(page.locator('#student-form [name=documento]')).toHaveCount(0);await expect(page.locator('#student-form')).not.toContainText('NUP');await page.locator('#student-form [name=nombre]').fill('Texto durante transición');await expect(page.locator('#student-form [name=nombre]')).toHaveValue('Texto durante transición');
   await page.emulateMedia({reducedMotion:'reduce'});const count=await page.evaluate(()=>window.screenArrivals||0);await page.evaluate(()=>location.hash='#/app/seguridad');await expect(page.locator('#security-form, #password-form, .main h2').first()).toBeVisible();assert.equal(await page.evaluate(()=>window.screenArrivals||0),count);assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.id==='inscolar-screen-arrival'&&a.playState==='running').length),0);assert.deepEqual(errors,[]);
  });
  await t.test('wizard → revisión → rechazo documental → corrección → aceptación',async()=>{
   const tutorUI=await pageFor('u002'), staffUI=await pageFor('u003');const page=tutorUI.page, personal=staffUI.page;
   await page.evaluate(()=>location.hash='#/app/inscripciones/nueva?inst=i001');await page.locator('#student-sel').selectOption('new');await page.locator('[name=new_nombre]').fill('Aspirante recorrido completo');await page.locator('[name=new_fecha]').fill('2015-01-01');await page.locator('#step-form button[type=submit]').click();await page.locator('[name=tutorPhone]').fill('8095550123');const cedula=page.locator('#wizard-tutor-id');await cedula.fill('00112345678');await expect(cedula).toHaveValue('001-1234567-8');assert.ok(await cedula.evaluate(el=>el.checkValidity()));assert.equal(await cedula.evaluate(el=>getComputedStyle(el).height),await page.locator('[name=tutorName]').evaluate(el=>getComputedStyle(el).height));await cedula.fill('00112');assert.equal(await cedula.evaluate(el=>el.checkValidity()),false);await cedula.fill('001-1234567-8');await page.locator('#step-form button[type=submit]').click();await page.locator('[name=gradoSolicitado]').selectOption('1ro de Primaria');await page.locator('[name=cicloEscolar]').selectOption('2026-2027');await page.locator('#btn-next-3').click();await page.locator('#file-0').setInputFiles({name:'acta.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nacta\n%%EOF')});await expect(page.locator('.remove-doc-btn')).toBeVisible();await page.locator('#btn-next-4').click();
   const submitted=page.waitForResponse(r=>r.request().method()==='POST' && r.url().endsWith('/api/enrollments'));await page.locator('#btn-submit-final').click();const result=await(await submitted).json();assert.equal(result.enrollment.estado,'Enviada');const id=result.enrollment.id;
   assert.ok((await(await staff.get('/api/enrollments?q='+id)).json()).enrollments.some(e=>e.id===id));
   await personal.evaluate(id=>location.hash='#/app/inscripciones/'+id+'/detalle',id);await personal.locator('[data-enrollment-action=revisar]').click();await personal.locator('#mod-confirm').click();await expect(personal.locator('.enrollment-state')).toContainText('En revisión');await expect(personal.locator('[data-enrollment-action=aceptar]')).toBeDisabled();await personal.getByRole('button',{name:'Abrir documentos',exact:true}).click();await personal.locator('.doc-reject-btn').click();await personal.locator('#rechazo-motivo').fill('El acta no es legible');await personal.locator('#mod-confirm').click();await expect(personal.locator('.main')).toContainText('El acta no es legible');
   await page.evaluate(id=>location.hash='#/app/inscripciones/'+id+'/detalle',id);await expect(page.locator('.enrollment-state')).toContainText('Documentos pendientes');await page.getByRole('button',{name:'Corregir documentos',exact:true}).click();await expect(page.locator('.main')).toContainText('El acta no es legible');await page.locator('#file-0').setInputFiles({name:'acta-corregida.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\ncorregida\n%%EOF')});await expect(page.locator('#btn-submit-corrections')).toBeEnabled();await page.locator('#btn-submit-corrections').click();await page.locator('#mod-confirm').click();await expect(page.locator('#btn-submit-corrections')).toHaveCount(0);
   await personal.evaluate(id=>location.hash='#/app/inscripciones/'+id+'/detalle',id);await expect(personal.locator('.enrollment-state')).toContainText('En revisión');await personal.getByRole('button',{name:'Abrir documentos',exact:true}).click();await personal.locator('.doc-accept-btn').click();await personal.locator('#mod-confirm').click();await expect(personal.locator('.main')).toContainText('Aprobado');
   await personal.evaluate(id=>location.hash='#/app/inscripciones/'+id+'/detalle',id);await expect(personal.locator('[data-enrollment-action=aceptar]')).toBeEnabled();await personal.locator('[data-enrollment-action=aceptar]').click();await expect(personal.getByRole('dialog')).toContainText('Aspirante recorrido completo');await personal.locator('#mod-confirm').evaluate(b=>{b.click();b.click();});await expect(personal.locator('.enrollment-state')).toContainText('Aceptada');
   await page.evaluate(id=>location.hash='#/app/inscripciones/'+id+'/detalle',id);await expect(page.locator('.enrollment-state')).toContainText('Aceptada');await expect(page.locator('.enrollment-history')).toContainText('Correcciones enviadas');const saved=await(await tutor.get('/api/enrollments/'+id)).json();assert.equal(saved.historial.filter(h=>h.accion==='Inscripción aceptada').length,1);assert.equal(saved.enrollment.disponibilidad.disponibles,0);assert.equal(saved.enrollment.contactoTutor.cedula,'00112345678');if(process.env.F54_SCREENSHOTS){await personal.screenshot({path:path.join(process.env.F54_SCREENSHOTS,'personal-aceptada.png'),fullPage:true,animations:'disabled'});await page.screenshot({path:path.join(process.env.F54_SCREENSHOTS,'tutor-aceptada.png'),fullPage:true,animations:'disabled'});}assert.deepEqual(tutorUI.errors,[]);assert.deepEqual(staffUI.errors,[]);
  });
  await t.test('estudiantes y aviso solo ante cambios reales, también al recuperar foco',async()=>{
   fixture('ui-list-update',{createdAt:'2026-12-01T00:00:00Z'});const {page,errors}=await pageFor('u002',{viewport:{width:375,height:812},colorScheme:'dark'});
   await page.evaluate(()=>location.hash='#/app/inscripciones');await expect(page.locator('.student-card').first()).toBeVisible();
   const checked=page.waitForResponse(r=>r.url().includes('/api/enrollments?'));
   await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await checked;
   await expect(page.locator('#enrollment-update')).toBeEmpty();
   assert.equal(await page.locator('.student-card').count(),db.students.filter(s=>s.tutorId==='u002').length+1);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);
   await mutate(staff,'ui-list-update','revisar');await expect(page.locator('#enrollment-update')).toContainText('Hay cambios');
   await page.locator('#refresh-enrollments').click();await expect(page.locator('#enrollment-update')).toBeEmpty();
   assert.deepEqual(errors,[]);
  });
  await t.test('una sola confirmación en las cinco etapas; cancelar conserva y salir limpia el wizard',async()=>{
   const {page,errors}=await pageFor('u002');
   await page.evaluate(()=>location.hash='#/app/inscripciones/nueva?inst=i001');
   await page.locator('#student-sel').selectOption('new');await page.locator('[name=new_nombre]').fill('Borrador navegación');await page.locator('[name=new_fecha]').fill('2015-01-01');
   for(let step=1;step<=5;step++){
    await page.locator('#sidebar [data-nav="\#/app/citas"]').click();
    await expect(page.getByRole('dialog')).toHaveCount(1);assert.ok(page.url().includes('/inscripciones/nueva'));
    await page.locator('#mod-cancel').click();await expect(page.getByRole('dialog')).toHaveCount(0);
    if(step<=2){if(step===2)await page.locator('[name=tutorPhone]').fill('8095550123');await page.locator('#step-form button[type=submit]').click();}
    if(step===3){await page.locator('[name=gradoSolicitado]').selectOption('1ro de Primaria');await page.locator('[name=cicloEscolar]').selectOption('2026-2027');await page.locator('#btn-next-3').click();}
    if(step===4){await page.locator('#file-0').setInputFiles({name:'acta.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nacta\n%%EOF')});await page.locator('#btn-next-4').click();}
   }
   await page.evaluate(()=>location.hash='#/app/citas');await expect(page.getByRole('dialog')).toHaveCount(1);assert.ok(page.url().includes('/inscripciones/nueva'));await page.locator('#mod-cancel').click();await expect(page.locator('#btn-submit-final')).toBeVisible();
   await page.route('**/api/drafts/*',async r=>{if(r.request().method()==='DELETE')await r.fulfill({status:500,contentType:'application/json',body:'{"error":"No se pudo abandonar"}'});else await r.continue();});
   await page.locator('#sidebar [data-nav="\#/app/citas"]').click();await page.locator('#mod-confirm').click();await expect(page.getByRole('dialog')).toHaveCount(1);await expect(page.locator('#mod-confirm')).toBeEnabled();assert.ok(page.url().includes('/inscripciones/nueva'));
   await page.unroute('**/api/drafts/*');await page.locator('#mod-confirm').click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.main h2')).toHaveText('Citas');
   await page.locator('#sidebar [data-nav="\#/app/inscripciones"]').click();await expect(page.locator('.main h2')).toHaveText('Inscripciones');await expect(page.getByRole('dialog')).toHaveCount(0);assert.deepEqual(errors,[]);
  });
  await t.test('otra sesión invalida acciones y foco correcto al cancelar el modal',async()=>{fixture('ui-stale');const {page,errors}=await pageFor('u003');await page.evaluate(()=>location.hash='#/app/inscripciones/ui-stale/detalle');await page.locator('[data-enrollment-action=rechazar]').click();await page.keyboard.press('Escape');await expect(page.locator('[data-enrollment-action=rechazar]')).toBeFocused();await mutate(admin,'ui-stale','revisar');// El aviso llega por SSE desde otra sesión, sin recargar ni esperar un intervalo.
await expect(page.locator('#enrollment-update')).toContainText('cambió');await expect(page.locator('[data-enrollment-action=rechazar]')).toBeDisabled();await page.locator('#refresh-enrollment').click();await expect(page.locator('.enrollment-state')).toContainText('En revisión');assert.deepEqual(errors,[]);});
 } finally {
  if(browser)await browser.close();for(const c of contexts){if(c.dispose)await c.dispose();else await c.close();}
  const exit=once(server,'exit');server.kill();if(server.exitCode===null && server.signalCode===null)await exit;
  for(const [f,bytes] of protectedFiles)if(bytes)assert.deepEqual(fs.readFileSync(path.join(root,f)),bytes);
  fs.rmSync(dir,{recursive:true,force:true});
 }
});
