const express=require('express');
const {save,load}=require('../lib/db');
const {requireAuth}=require('../lib/middleware');
const service=require('../lib/appointment-service');
const updates=require('../lib/appointment-updates');
const router=express.Router();router.use(requireAuth);
function handle(fn){return(req,res)=>{try{fn(req,res);}catch(e){res.status(e.status||500).json({error:e.status?e.message:'No se pudo guardar o consultar la cita. Reintenta.'});}};}
function appointment(req){const a=req.db.appointments.find(a=>a.id===req.params.id);if(!a)throw Object.assign(Error('Cita no encontrada.'),{status:404});if(!service.read(req.currentUser,a))throw Object.assign(Error('No tienes acceso a esta cita.'),{status:403});return a;}
function institution(req,id){const i=req.db.institutions.find(i=>i.id===id);if(!i)throw Object.assign(Error('Institución no encontrada.'),{status:404});if(req.currentUser.role==='Personal de institución'&&!service.staff(req.currentUser,id))throw Object.assign(Error('No puedes consultar otra institución.'),{status:403});return i;}
router.get('/appointments/events',(req,res)=>{if(!['Tutor','Personal de institución'].includes(req.currentUser.role))return res.status(403).json({error:'No tienes acceso a citas.'});res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.flushHeaders();res.write(': conectado\n\n');const id=req.currentUser.id;
 const listener=change=>{const u=load().users.find(u=>u.id===id&&u.estado!=='Inactivo');if(!u){res.end();return;}if(service.staff(u,change.institucionId)||(u.role==='Tutor'&&(!change.tutorId||change.tutorId===u.id)))res.write('event: changed\ndata: {}\n\n');};updates.on('changed',listener);const timer=setInterval(()=>res.write(': activo\n\n'),30000);req.on('close',()=>{clearInterval(timer);updates.off('changed',listener);});});
router.get('/appointments/availability',handle((req,res)=>{const id=req.query.institucionId;const i=institution(req,id);let exclude=null;if(req.query.excludeId){const a=req.db.appointments.find(a=>a.id===req.query.excludeId);if(!a||!service.read(req.currentUser,a)||a.institucionId!==id)throw Object.assign(Error('No puedes consultar esta cita.'),{status:403});exclude=a.id;}
 const month=req.query.mes||service.dateKey(new Date()).slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Object.assign(Error('Selecciona un mes válido.'),{status:400});res.json({institucion:{id:i.id,nombre:i.nombre},mes:month,zonaHoraria:service.TIME_ZONE,slots:(i.estado||'Activo')==='Activo'?service.available(req.db,id,month,exclude):[]});}));
router.post('/institutions/:id/appointment-slots',handle((req,res)=>{institution(req,req.params.id);const slots=service.configure(req.db,req.currentUser,req.params.id,req.body||{});save(req.db);updates.publish({institucionId:req.params.id});res.json({slots,zonaHoraria:service.TIME_ZONE});}));
router.get('/appointments',handle((req,res)=>{const u=req.currentUser;if(!['Tutor','Personal de institución'].includes(u.role))throw Object.assign(Error('No tienes acceso a citas.'),{status:403});let list=req.db.appointments.filter(a=>service.read(u,a));const {estado,fecha,grupo}=req.query;
 if(estado&&estado!=='Todos')list=list.filter(a=>service.status(a)===estado);
 if(fecha){if(!/^\d{4}-\d{2}-\d{2}$/.test(fecha))throw Object.assign(Error('Fecha inválida.'),{status:400});list=list.filter(a=>service.dateKey(service.when(a))===fecha);}
 if(grupo==='proximas')list=list.filter(a=>service.ACTIVE.includes(a.estado)&&new Date(service.when(a))>=new Date());
 if(grupo==='anteriores')list=list.filter(a=>!service.ACTIVE.includes(a.estado)||new Date(service.when(a))<new Date());
 list.sort((a,b)=>new Date(service.when(a))-new Date(service.when(b))||a.id.localeCompare(b.id));const total=list.length;
 const paged=req.query.page!==undefined||req.query.limit!==undefined;const page=Number(req.query.page||1),limit=Number(req.query.limit||10);if(!Number.isInteger(page)||page<1||!Number.isInteger(limit)||limit<1||limit>100)throw Object.assign(Error('Paginación inválida.'),{status:400});if(paged)list=list.slice((page-1)*limit,page*limit);res.json({total,page,limit,appointments:list.map(a=>service.dto(req.db,u,a)),zonaHoraria:service.TIME_ZONE});}));
router.get('/appointments/:id',handle((req,res)=>res.json({appointment:service.dto(req.db,req.currentUser,appointment(req))})));
router.post('/appointments',handle((req,res)=>{const {appointment:a,replayed}=service.create(req.db,req.currentUser,req.body||{});if(!replayed){save(req.db);updates.publish(a);}res.json({appointment:service.dto(req.db,req.currentUser,a),replayed});}));
for(const action of ['aceptar','rechazar','cancelar','reprogramar','confirmar'])router.post('/appointments/:id/'+action,handle((req,res)=>{const a=appointment(req);if(action==='confirmar'&&req.body?.fechaHoraConfirmada&&req.body.fechaHoraConfirmada!==a.fechaHoraSolicitada)throw Object.assign(Error('Usa Reprogramar para cambiar el horario.'),{status:400});service.transition(req.db,req.currentUser,a,action==='confirmar'?'aceptar':action,req.body||{});save(req.db);updates.publish(a);res.json({appointment:service.dto(req.db,req.currentUser,a)});}));
module.exports=router;
